import "../load-env.js";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { closeDb, rawPool } from "./index.js";

/**
 * The migration runner.
 *
 * Deliberately tiny and dependency-free: it reads migrations/*.sql in
 * filename order, runs each one inside a transaction, and records it. Running
 * it twice does nothing the second time, which is what lets it sit in Render's
 * build command without anyone remembering to run it.
 *
 * Migrations are plain SQL rather than generated by drizzle-kit so that what
 * runs against production is exactly what was reviewed.
 */
const here = dirname(fileURLToPath(import.meta.url));
/* src/db in dev, dist/db once compiled — migrations/ sits at the package root. */
const migrationsDir = resolve(here, "../../migrations");

async function main() {
  const pool = rawPool();

  await pool.query(`
    CREATE TABLE IF NOT EXISTS _migrations (
      name       text PRIMARY KEY,
      applied_at timestamptz NOT NULL DEFAULT now()
    )
  `);

  const { rows } = await pool.query<{ name: string }>("SELECT name FROM _migrations");
  const applied = new Set(rows.map((r) => r.name));

  const files = readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  let ran = 0;
  for (const file of files) {
    if (applied.has(file)) continue;

    const sql = readFileSync(join(migrationsDir, file), "utf8");
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await client.query(sql);
      await client.query("INSERT INTO _migrations (name) VALUES ($1)", [file]);
      await client.query("COMMIT");
      console.log(`[migrate] applied ${file}`);
      ran += 1;
    } catch (err) {
      await client.query("ROLLBACK");
      console.error(`[migrate] FAILED on ${file}`);
      throw err;
    } finally {
      client.release();
    }
  }

  console.log(
    ran === 0
      ? `[migrate] up to date (${files.length} migrations)`
      : `[migrate] ${ran} applied`,
  );
}

main()
  .then(() => closeDb())
  .then(() => process.exit(0))
  .catch(async (err) => {
    console.error(err);
    await closeDb().catch(() => {});
    process.exit(1);
  });
